package com.test.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-06-05T21:56:19.014+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://order.test.com", name = "OrderEndpoint")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OrderEndpoint {

    @WebMethod(action = "http://order.test.com/Order")
    @WebResult(name = "resultCode", targetNamespace = "http://order.test.com", partName = "resultCode")
    public java.lang.String order(
        @WebParam(partName = "partName", name = "partName", targetNamespace = "http://order.test.com")
        java.lang.String partName,
        @WebParam(partName = "amount", name = "amount", targetNamespace = "http://order.test.com")
        int amount,
        @WebParam(partName = "customerName", name = "customerName", targetNamespace = "http://order.test.com")
        java.lang.String customerName
    );
}
